Repository testcontainers/testcontainers-python, pull requests merged in 2023-04, with the labels that each got.

#296 Remove class-level variables from containers.
  arangodb/testcontainers/arangodb/__init__.py
  arangodb/tests/test_arangodb.py
  azurite/testcontainers/azurite/__init__.py
  clickhouse/testcontainers/clickhouse/__init__.py
  compose/testcontainers/compose/__init__.py
  core/testcontainers/core/config.py
  core/testcontainers/core/docker_client.py
  core/testcontainers/core/generic.py
  core/testcontainers/core/utils.py
  core/testcontainers/core/waiting_utils.py
  core/tests/test_docker_in_docker.py
  core/tests/test_new_docker_api.py
  elasticsearch/testcontainers/elasticsearch/__init__.py
  google/testcontainers/google/__init__.py
  google/testcontainers/google/pubsub.py
  kafka/testcontainers/kafka/__init__.py
  kafka/tests/test_kafka.py
  keycloak/testcontainers/keycloak/__init__.py
  keycloak/tests/test_keycloak.py
  localstack/testcontainers/localstack/__init__.py
  localstack/tests/test_localstack.py
  minio/testcontainers/minio/__init__.py
  mongodb/testcontainers/mongodb/__init__.py
  mongodb/tests/test_mongodb.py
  mssql/testcontainers/mssql/__init__.py
  mysql/testcontainers/mysql/__init__.py
  neo4j/testcontainers/neo4j/__init__.py
  nginx/testcontainers/nginx/__init__.py
  nginx/tests/test_nginx.py
  opensearch/testcontainers/opensearch/__init__.py
  oracle/testcontainers/oracle/__init__.py
  postgres/testcontainers/postgres/__init__.py
  rabbitmq/testcontainers/rabbitmq/__init__.py
  redis/testcontainers/redis/__init__.py
  requirements/3.10.txt
  requirements/3.7.txt
  requirements/3.8.txt
  requirements/3.9.txt
  selenium/testcontainers/selenium/__init__.py
Labels: 👀 requires attention

#317 Add Python3.11 to build matrix
  .github/workflows/main.yml
  Makefile
  meta/setup.py
  requirements/3.11.txt
Labels: 🚀 enhancement, 🔧 maintenance

#333 Update google-cloud-pubsub to major version 2.
  google/setup.py
  google/testcontainers/google/pubsub.py
  google/tests/test_google.py
  requirements/3.10.txt
  requirements/3.11.txt
  requirements/3.7.txt
  requirements/3.8.txt
  requirements/3.9.txt
Labels: 🔧 maintenance, 📦 package: google
