Repository testcontainers/testcontainers-python, pull requests merged in 2023-01, with the labels that each got.

#208 Add ResourceCleaner for stop containers after exit (#104)
  testcontainers/core/docker_client.py
Labels: awaiting response

#293 More informative logs in `waiting_utils`.
  core/testcontainers/core/waiting_utils.py
Labels: enhancement, package: core

#295 Add type annotations and improve documentation.
  arangodb/testcontainers/arangodb/__init__.py
  azurite/testcontainers/azurite/__init__.py
  clickhouse/testcontainers/clickhouse/__init__.py
  compose/testcontainers/compose/__init__.py
  core/testcontainers/core/container.py
  core/testcontainers/core/docker_client.py
  core/testcontainers/core/exceptions.py
  core/testcontainers/core/generic.py
  core/testcontainers/core/utils.py
  core/testcontainers/core/waiting_utils.py
  elasticsearch/testcontainers/elasticsearch/__init__.py
  google/testcontainers/google/pubsub.py
  kafka/testcontainers/kafka/__init__.py
  keycloak/testcontainers/keycloak/__init__.py
  localstack/testcontainers/localstack/__init__.py
  minio/testcontainers/minio/__init__.py
  mongodb/testcontainers/mongodb/__init__.py
  mssql/testcontainers/mssql/__init__.py
  mysql/testcontainers/mysql/__init__.py
  neo4j/testcontainers/neo4j/__init__.py
  nginx/testcontainers/nginx/__init__.py
  opensearch/testcontainers/opensearch/__init__.py
  oracle/testcontainers/oracle/__init__.py
  postgres/testcontainers/postgres/__init__.py
  rabbitmq/testcontainers/rabbitmq/__init__.py
  redis/testcontainers/redis/__init__.py
  selenium/testcontainers/selenium/__init__.py
Labels: maintenance, documentation
