Repository testcontainers/testcontainers-python, pull requests merged in 2024-05, with the labels that each got.

#565 fix(keycloak): add realm imports
  modules/keycloak/testcontainers/keycloak/__init__.py
Labels: community-feat

#552 fix(mysql): Add seed support in MySQL
  core/testcontainers/core/generic.py
  modules/mysql/testcontainers/mysql/__init__.py
  modules/mysql/tests/seeds/01-schema.sql
  modules/mysql/tests/seeds/02-seeds.sql
  modules/mysql/tests/test_mysql.py
Labels: community-feat

#322 fix: Add memcached container
  index.rst
  modules/memcached/README.rst
  modules/memcached/setup.py
  modules/memcached/testcontainers/memcached/__init__.py
  modules/memcached/tests/test_memcached.py
  poetry.lock
  pyproject.toml
Labels: ✨ package: new, community-feat

#364 fix: Add selenium video support #6
  modules/selenium/testcontainers/selenium/__init__.py
  modules/selenium/testcontainers/selenium/video.py
  modules/selenium/tests/test_selenium.py
Labels: feat, needs-rebase, community-feat

#561 fix: added types to exec & tc_properties_get_tc_host
  core/testcontainers/core/config.py
  core/testcontainers/core/container.py
Labels: 👀 requires attention

#566 feat(core): Private registry
  core/testcontainers/core/config.py
  core/testcontainers/core/docker_client.py
  core/testcontainers/core/utils.py
  core/tests/test_docker_client.py
  core/tests/test_utils.py
Labels: 👀 requires attention
