Repository testcontainers/testcontainers-python, pull requests merged in 2024-03, with the labels that each got.

#426 feat(compose)!: implement compose v2 with improved typing
  core/testcontainers/compose/__init__.py
  core/testcontainers/compose/compose.py
  core/testcontainers/core/exceptions.py
  core/tests/compose_fixtures/basic/docker-compose.yaml
  core/tests/compose_fixtures/port_multiple/compose.yaml
  core/tests/compose_fixtures/port_single/compose.yaml
  core/tests/test_compose.py
Labels: 🛟 help wanted

#428 fix(clickhouse): clickhouse waiting
  modules/clickhouse/testcontainers/clickhouse/__init__.py
Labels: 4.0.1

#380 fix: Close docker client when stopping the docker container
  core/testcontainers/core/container.py
Labels: 👀 requires attention

#341 fix: Update the copyright header for readthedocs
  conf.py
Labels: 📖 documentation

#445 feat(postgres): Remove SqlAlchemy dependency from postgres container
  INDEX.rst
  README.md
  modules/postgres/testcontainers/postgres/__init__.py
  modules/postgres/tests/test_postgres.py
  poetry.lock
  pyproject.toml
Labels: 4.1.0, 4.0.1

#413 feat: support influxdb
  INDEX.rst
  modules/influxdb/README.rst
  modules/influxdb/testcontainers/influxdb.py
  modules/influxdb/testcontainers/influxdb1/__init__.py
  modules/influxdb/testcontainers/influxdb2/__init__.py
  modules/influxdb/tests/__init__.py
  modules/influxdb/tests/test_influxdb.py
  poetry.lock
  pyproject.toml
Labels: 👀 requires attention, 4.1.0

#368 fix(core): DinD issues #141, #329
  core/testcontainers/core/docker_client.py
  core/tests/test_docker_in_docker.py
Labels: 👀 requires attention, 4.1.0

#377 fix(kafka): wait_for_logs in kafka container to reduce lib requirement
  modules/kafka/testcontainers/kafka/__init__.py
  poetry.lock
  pyproject.toml
Labels: 👀 requires attention, feat

#164 fix: pass updated keyword args to Publisher/Subscriber client in google/pubsub #161
  modules/google/testcontainers/google/pubsub.py
Labels: 📦 package: google, community-feat

#508 fix(google): add support for Datastore emulator
  modules/google/README.rst
  modules/google/testcontainers/google/__init__.py
  modules/google/testcontainers/google/datastore.py
  modules/google/tests/test_google.py
  poetry.lock
  pyproject.toml
Labels: community-feat

#492 fix: Add Weaviate module
  index.rst
  modules/weaviate/README.rst
  modules/weaviate/testcontainers/weaviate/__init__.py
  modules/weaviate/tests/test_weaviate.py
  poetry.lock
  pyproject.toml
Labels: community-feat

#476 fix: Add CassandraContainer
  .github/settings.yml
  index.rst
  modules/cassandra/README.rst
  modules/cassandra/testcontainers/cassandra/__init__.py
  modules/cassandra/tests/test_cassandra.py
  poetry.lock
  pyproject.toml
Labels: community-feat

#463 fix: Qdrant module
  conf.py
  index.rst
  modules/qdrant/README.rst
  modules/qdrant/testcontainers/qdrant/__init__.py
  modules/qdrant/tests/test_config.yaml
  modules/qdrant/tests/test_qdrant.py
  poetry.lock
  pyproject.toml
Labels: community-feat

#462 fix(nats): Client-Free(ish) NATS container
  index.rst
  modules/nats/README.rst
  modules/nats/testcontainers/nats/__init__.py
  modules/nats/tests/test_nats.py
  poetry.lock
  pyproject.toml
Labels: community-feat

#441 fix(kafka): Add redpanda testcontainer module
  modules/kafka/README.rst
  modules/kafka/testcontainers/kafka/__init__.py
  modules/kafka/testcontainers/kafka/_redpanda.py
  modules/kafka/tests/test_redpanda.py
  poetry.lock
  pyproject.toml
Labels: community-feat

#389 feat(new): add a new Docker Registry test container
  index.rst
  modules/registry/README.rst
  modules/registry/testcontainers/registry/__init__.py
  modules/registry/tests/test_registry.py
  poetry.lock
  pyproject.toml
Labels: ✨ package: new, community-feat

#363 fix: Improved Oracle DB module
  index.rst
  modules/oracle-free/README.rst
  modules/oracle-free/testcontainers/oracle/__init__.py
  modules/oracle-free/tests/test_oracle.py
  modules/oracle/testcontainers/oracle/__init__.py
  modules/oracle/tests/test_oracle.py
  poetry.lock
  pyproject.toml
Labels: feat, community-feat
